// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thpt.ThachBan.DTO.Models
{
    public partial class Account
    {
        public Guid AccountId { get; set; }
        public int Status { get; set; }
        public string Password { get; set; }
        public Guid RoleId { get; set; }
        public string AccountCode { get; set; }

        public virtual Role Role { get; set; }
    }
}