// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thpt.ThachBan.DTO.Models
{
    public partial class Class
    {
        public Class()
        {
            Schedule = new HashSet<Schedule>();
            Student = new HashSet<Student>();
        }

        public Guid ClassId { get; set; }
        public string ClassName { get; set; }
        public int NumOfMem { get; set; }
        public int NumOfSeat { get; set; }
        public int Grade { get; set; }
        public Guid? EmployeeId { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}