// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thpt.ThachBan.DTO.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Class = new HashSet<Class>();
            DepartmentManager = new HashSet<DepartmentManager>();
            Schedule = new HashSet<Schedule>();
            Subject = new HashSet<Subject>();
        }

        public Guid EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public int Gender { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Nation { get; set; }
        public string Address { get; set; }
        public DateTime WorkEnded { get; set; }
        public DateTime WorkStarted { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }

        public virtual ICollection<Class> Class { get; set; }
        public virtual ICollection<DepartmentManager> DepartmentManager { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }

        public virtual ICollection<Subject> Subject { get; set; }
    }
}