// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thpt.ThachBan.DTO.Models
{
    public partial class Guardian
    {
        public Guid GuardianId { get; set; }
        public string GuardianName { get; set; }
        public string Career { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int? Relation { get; set; }
        public Guid? StudentId { get; set; }

        public virtual Student Student { get; set; }
    }
}