// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace thpt.ThachBan.DTO.Models
{
    public partial class Schedule
    {
        public Guid ClassId { get; set; }
        public int Day { get; set; }
        public int ClassTime { get; set; }
        public Guid? SubjectId { get; set; }
        public Guid? EmpoyeeId { get; set; }
        public virtual Class Class { get; set; }
        public virtual Employee Empoyee { get; set; }
        public virtual Subject Subject { get; set; }
    }
}