// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thpt.ThachBan.DTO.Models
{
    public partial class SocialPolicy
    {
        public SocialPolicy()
        {
            Student = new HashSet<Student>();
        }

        public Guid SocialPolicyId { get; set; }
        public string SocialPolicyName { get; set; }
        public double ScholarshipLevel { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Student> Student { get; set; }
    }
}