// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace thpt.ThachBan.DTO.Models
{
    public partial class Subject
    {
        public Subject()
        {
            Result = new HashSet<Result>();
            Schedule = new HashSet<Schedule>();
            Employee = new HashSet<Employee>();
        }

        public Guid SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string Description { get; set; }
        public int MaxLessonAday { get; set; }
        public int LessonAweek { get; set; }
        public Guid DepartmentId { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Result> Result { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
    }
}